function Untitled1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled1 = importfile("C:\Users\sjspenc\Documents\MATLAB\new_Tau_tests\6-15-2021_16-55-16.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jun-2021 12:26:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timeStamp", "UIWaveMakerMode", "UIWaveMakerPos", "UIWaveMakerHeight", "UIWaveMakerFrequency", "UIWaveMakerSigH", "UIWaveMakerPeakF", "UIWaveMakergamma", "UIWecMode", "UIWecTorque", "UIWeckP", "UIWeckD", "UIWecSigH", "UIWecPeakF", "UIWecgamma", "probe1", "probe2", "waveMakerPos", "waveMakerDebugData", "wecPos", "wecTau", "wecPower", "wecVel"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Untitled1 = readtable(filename, opts);

end